{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restaurant-service.fullname" . }}-secrets
  labels:
    {{- include "restaurant-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.database-url }}
  database-url: {{ .Values.secrets.database-url | b64enc }}
  {{- end }}
  {{- if .Values.secrets.redis-url }}
  redis-url: {{ .Values.secrets.redis-url | b64enc }}
  {{- end }}
  {{- if .Values.secrets.kafka-brokers }}
  kafka-brokers: {{ .Values.secrets.kafka-brokers | b64enc }}
  {{- end }}
{{- end }}
