{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.database-url }}
  database-url: {{ index .Values.secrets "database-url" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.redis-url }}
  redis-url: {{ index .Values.secrets "redis-url" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwt-secret }}
  jwt-secret: {{ index .Values.secrets "jwt-secret" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwt-refresh-secret }}
  jwt-refresh-secret: {{ index .Values.secrets "jwt-refresh-secret" | b64enc }}
  {{- end }}
{{- end }}
