apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: food-delivery-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: food-delivery

  source:
    repoURL: https://github.com/brixxdd/Proyeceto-personal
    targetRevision: main
    path: argocd/apps/services

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
